"""baseline schema

Revision ID: 6137a296ea9d
Revises: 
Create Date: 2026-09-15 22:36:59.773959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6137a296ea9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('invite_code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('household_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_household_id'), ['household_id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("account_type IN ('bank', 'cash', 'wallet')", name='ck_account_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('credit_cards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('total_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('statement_day', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('due_day BETWEEN 1 AND 31', name='ck_cc_due_day'),
    sa.CheckConstraint('statement_day BETWEEN 1 AND 31', name='ck_cc_statement_day'),
    sa.CheckConstraint('total_limit >= 0', name='ck_cc_total_limit_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_cards_user_id'), ['user_id'], unique=False)

    op.create_table('loans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('loan_type', sa.String(length=30), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('outstanding_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("loan_type IN ('personal', 'home', 'auto', 'education', 'other')", name='ck_loan_type'),
    sa.CheckConstraint('interest_rate >= 0', name='ck_loan_rate_nonneg'),
    sa.CheckConstraint('outstanding_balance >= 0', name='ck_loan_outstanding_nonneg'),
    sa.CheckConstraint('principal_amount > 0', name='ck_loan_principal_positive'),
    sa.CheckConstraint('tenure_months > 0', name='ck_loan_tenure_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_user_id'), ['user_id'], unique=False)

    op.create_table('recurring_incomes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_household_shared', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_posted_period', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_recurring_income_positive'),
    sa.CheckConstraint('day_of_month >= 1 AND day_of_month <= 31', name='ck_recurring_income_day'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_recurring_income_user')
    )
    with op.batch_alter_table('recurring_incomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_incomes_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_incomes_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_household_shared', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=True),
    sa.Column('credit_card_id', sa.String(length=32), nullable=True),
    sa.Column('loan_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("transaction_type IN ('income', 'expense', 'transfer')", name='ck_txn_type'),
    sa.CheckConstraint('amount > 0', name='ck_txn_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_txn_account', ['account_id'], unique=False)
        batch_op.create_index('ix_txn_credit_card', ['credit_card_id', 'transaction_type'], unique=False)
        batch_op.create_index('ix_txn_household', ['user_id', 'is_household_shared'], unique=False)
        batch_op.create_index('ix_txn_loan', ['loan_id', 'transaction_type'], unique=False)
        batch_op.create_index('ix_txn_user_date', ['user_id', 'transaction_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_user_date')
        batch_op.drop_index('ix_txn_loan')
        batch_op.drop_index('ix_txn_household')
        batch_op.drop_index('ix_txn_credit_card')
        batch_op.drop_index('ix_txn_account')

    op.drop_table('transactions')
    with op.batch_alter_table('recurring_incomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_incomes_user_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_incomes_account_id'))

    op.drop_table('recurring_incomes')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_user_id'))

    op.drop_table('loans')
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_cards_user_id'))

    op.drop_table('credit_cards')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_user_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_household_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('households')
    # ### end Alembic commands ###
